pipeline {
    agent {
        docker {
            image 'python:3.8-slim'
            args '--user root'
        }
    }

    stages {
        stage('Test') {
            steps {
                sh 'pip install --user pytest'
                sh 'export PATH=$HOME/.local/bin:$PATH && pytest --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
    }
}
